### ISSUE TITLE
連桿問題

### ISSUE THREAD

**Issue by kmolLin** [kmollee/django-project-template#1]
學長你如何判斷你的連桿是上三角(朝上)還是下三角(朝下)，還是只有正三角(朝上)
在演算法裡面的test.py

**Comment by kmollee** [comment]
Hi, 

當初似乎是只有正的, 不過你只要每次在產生三角的時候
多加一個 binary 變數(正 | 反)就可以來確定方向, 就可以產生出對應的三角頂點
之後就繼續三角堆疊, 不論幾個連桿都可以疊, 如果你矩陣用的還OK, 直接用矩陣算會好很多
由演算法來決定這個正反就好, 現在看起來 當初處裡的方式 粗糙不堪

應該可以在 language 上在寫一個 interpreter or package 專門處理機構構建,  這樣可以抽象很多 節省很多時間 重用性也很高

幫我向嚴老師問聲好 謝謝

have nice day.
